last commit on m1 max

diff --git a/scripts/bunny b/scripts/bunny
--- a/scripts/bunny
+++ b/scripts/bunny
@@ -27,10 +27,79 @@ function log() {
 }
 
 function error() {
-  printf "%b\\n" "${*}" >&2
+  printf "%b\\n" "${RED}${BOLD}ERR:${RESET}${*}" >&2
 
   exit 1
 }
+
+# error_handler()
+#
+# Handles error when they are caught
+function error_handler() {
+    local -r exit_code="$?"
+    local -r _line_number="$1"
+    local -r command="$2"
+
+    # shellcheck disable=SC2016
+    if is_bound command && [[ "$command" != 'return $code' ]]; then
+        log "  [${RED}x${RESET}] ${BOLD}ERROR ${DIM}${RED}$exit_code${RESET}${BOLD} → ${command}${RESET} "
+    fi
+    log ""
+
+    for i in "${!BASH_SOURCE[@]}"; do
+        if ! contains "errors.sh" "${BASH_SOURCE[$i]:-unknown}"; then
+            log "    - ${FUNCNAME[$i]:-unknown}() ${ITALIC}${DIM}at line${RESET} ${BASH_LINENO[$i-1]:-unknown} ${ITALIC}${DIM}in${RESET} $(error_path "${BASH_SOURCE[$i]:-unknown}")"
+        fi
+    done
+    log ""
+}
+
+# contains <find> <content>
+# 
+# given the "content" string, all other parameters passed in
+# will be looked for in this content.
+function contains() {
+    local -r find="${1}"
+    local -r content="${2}"
+
+    if is_empty "$find"; then
+        error "contains("", ${content}) function did not recieve a FIND string! This is an invalid call!" 1
+    fi
+
+    if is_empty "$content"; then
+        debug "contains" "contains(${find},"") received empty content so always returns false"
+        return 1;
+    fi
+
+    if [[ "${content}" =~ ${find} ]]; then
+        debug "contains" "found: ${find}"
+        return 0 # successful match
+    fi
+
+    debug "contains" "not found: ${find}"
+    return 1
+}
+
+
+# catch_errors()
+#
+# Catches all errors found in a script -- including pipeline errors -- and
+# sends them to an error handler to report the error.
+function catch_errors() {
+    set -Eeuo pipefail
+    trap 'error_handler $LINENO "$BASH_COMMAND"' ERR
+}
+
+# allow_errors()
+#
+# Allows for non-zero return-codes to avoid being sent to the error_handler
+# and is typically used to temporarily check on an external state from the shell
+# where an error might be encountered but which will be handled locally
+function allow_errors() {
+    set +Eeuo pipefail
+    trap - ERR
+}
+
 
 # debug <fn> <msg> <...>
 # 
@@ -57,6 +126,64 @@ function debug() {
     fi
 }
 
+function has_characters() {
+    local -r char_str="${1:?has_characters() did not recieve a CHARS string!}"
+    local -r content="${2:?content expression not passed to has_characters()}"
+
+    if [[ "$content" == *["$char_str"]* ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+function is_bound() {
+    allow_errors
+    local -n __test_by_ref=$1 2>/dev/null || { debug "is_bound" "unbounded ref";  return 1; }
+    local -r by_val="${1}:-"
+    local name="${!__test_by_ref}" 2>/dev/null
+    local -r arithmetic='→+-=><%'
+    if has_characters "${arithmetic}" "$1"; then
+        debug "is_bound" "${name} is NOT bound"
+        return 1
+    else
+        local idx=${!1} 2>/dev/null 
+        local a="${__test_by_ref@a}" 
+
+        if [[ -z "${idx}${a}" ]]; then
+            debug "is_bound" "${name} is NOT bound: ${idx}, ${a}"
+            catch_errors
+            return 1
+        else 
+            debug "is_bound" "${name} IS bound: ${idx}, ${a}"
+            catch_errors
+            return 0
+        fi
+    fi
+}
+
+# lc() <str>
+#
+# converts the passed in <str> to lowercase
+function lc() {
+    local -r str="${1-}"
+    echo "${str}" | tr '[:upper:]' '[:lower:]'
+}
+
+# not_empty() <test>
+# 
+# tests whether the <test> value passed in is an empty string (or is unset)
+# and returns 0 when it is NOT empty and 1 when it is.
+function not_empty() {
+    if [ -z "$1" ] || [[ "$1" == "" ]]; then
+        debug "not_empty" "WAS empty, returning 1/false"
+        return 1
+    else
+        debug "not_empty" "was not empty [${#1} chars], returning 0/true"
+        return 0
+    fi
+}
+
 # is_array() <ref:var>
 #
 # tests whether the passed in variable reference is
@@ -68,8 +195,10 @@ function debug() {
 # Note: this check only works after the variable passed in
 # is actually set and set -u is in effect
 function is_array() {
+    allow_errors
     local -n __var__=$1 2>/dev/null
     local -r test=${__var__@a} 2>/dev/null
+    catch_errors
 
     if is_bound __var__; then
         if not_empty "$test" && [[ $test = a ]]; then
@@ -83,10 +212,9 @@ function is_array() {
         debug "is_array" "is_array was called without a reference so returning false!"
         return 1
     fi
-
 }
 
-# is_empty() <test | ref:test>
+# is_empty() <test>
 # 
 # tests whether the <test> value passed in is an empty string (or is unset)
 # and returns 0 when it is empty and 1 when it is NOT.
@@ -128,12 +256,11 @@ function has_command() {
 # ends_with <look-for> <content>
 function ends_with() {
     local -r look_for="${1:?No look-for string provided to ends_with}"
-    local -r content="${2}"
+    local -r content="${2:-}"
     local -r no_suffix="${content%"${look_for}"}"
 
     if is_empty "${content}"; then
-        debug "ends_with" "ends_with(${look_for}, "") was passed empty content so will always return false"
-        return 1;
+      error "call to ends_with(${look_for}) received no content to test!"  
     fi
 
     if [[ "${content}" == "${no_suffix}" ]]; then
@@ -146,36 +273,41 @@ function ends_with() {
 }
 
 function push() {
+    allow_errors
+    # shellcheck disable=SC2178
     local -n __array__=$1
+    # parameter for use when passed by value
     local -ra params=( "$@" )
     local -ra __params__=("${params[@]:1}")
+    catch_errors
 
-    if is_array __array__; then
-      __array__+=(_ref_key "${__params_[@]}")
-      return 0
-    fi
+    __array__+=("${__params__[@]}")
+
 }
 
+
 function runtime_family() {
-  local -r filepath="${1:?no filepath provideded!}"
-  if ends_with ".ts"; then
+  local -r filepath="${1:?no filepath provided!}"
+  if ends_with ".ts" "${filepath}"; then
     echo "ts"
-  elif ends_with ".tsx"; then 
+  elif ends_with ".tsx" "${filepath}"; then 
     echo "ts"
-  elif ends_with ".mts"; then
+  elif ends_with ".mts" "${filepath}"; then
     echo "ts"
-  elif ends_with ".cts"; then
+  elif ends_with ".cts" "${filepath}"; then
     echo "ts"
-  elif ends_with ".wasm"; then
+  elif ends_with ".wasm" "${filepath}"; then
     echo "wasm"
-  elif ends_with ".wat"; then
+  elif ends_with ".wat" "${filepath}"; then
     echo "wasm"
-  elif ends_with ".js"; then
+  elif ends_with ".js" "${filepath}"; then
     echo "js"
-  elif ends_with ".mjs"; then
+  elif ends_with ".mjs" "${filepath}"; then
     echo "js"
-  elif ends_with ".cjs"; then
+  elif ends_with ".cjs" "${filepath}"; then
     echo "js"
+  else 
+    error "unknown file type based on file extension: ${filepath}"
   fi
 }
 
@@ -187,13 +319,13 @@ function runtime_family() {
 # and which are not.
 function detect_runtime {
   local -r filepath="${1:?no filepath provided}"
-  local -n __avail
-  local -n __unavail
-  local -r family=ends_with ".ts" "$filepath" && echo "ts" || ends_with ".tsx" && echo "ts" || echo "js"
+  local -n __avail=$2
+  local -n __unavail=$3
+  local -r family="$(runtime_family "${filepath}")" 
   local -a avail=()
   local -a unavail=()
 
-  case "$family" in
+  case "${family}" in
 
     ts)
 
@@ -220,7 +352,13 @@ function detect_runtime {
       else
         push unavail "ts-node"
       fi
-      break
+      
+      if has_command "nix-shell"; then
+        push avail "nix-shell";
+      else
+        push unavail "nix-shell"
+      fi
+
       ;;
     
     wasm)
@@ -241,78 +379,41 @@ function detect_runtime {
       else
         push unavail 'nix-shell';
       fi
-      break
+
       ;;
 
     js)
-      if has_command 'bun'; then
-        push avail 'bun'
-┆     else
-┆       push unavail 'bun'
-┆     fi
+
+      if has_command "bun"; then
+        push avail "bun"
+      else
+        push unavail "bun"
+      fi
 
       if has_command 'node'; then
         push avail 'node';
-      else 
+      else
         push unavail 'node';
       fi
-┆   
-┆     if has_command 'deno'; then
-┆       push avail 'deno';
-┆     else
-┆       push unavail 'deno';
-┆     fi
+
+      if has_command 'deno'; then
+        push avail 'deno';
+      else
+        push unavail 'deno';
+      fi
 
       if has_command 'nix-shell'; then
         push avail 'nix-shell';
       else
         push unavail 'nix-shell';
       fi
-      break
       ;;
 
     *)
       error "Unknown file type passed in for bunny run: ${BOLD}${filepath}${RESET}"
-      exit 1
   esac
 
-  __avail=avail
-  __unavail=unavail
+  __avail=( "${avail[@]}" )
+  __unavail=( "${unavail[@]}" )
 }
 
-if is_empty "${1:-}"; then
-  error "no target program given for ${BOLD}bunny${RESET} to run!"
-else 
-  if ! file_exists "$1"; then 
-    error "the target program ${BLUE}$1${RESET} ${ITALIC}does not${RESET} exist!"
-  fi
-fi
-
-if is_wasm "$1"; then 
-  if has_command "wasmer"; then 
-    wasmer "$1"
-  elif has_command "wasmtime"; then 
-    wasmtime "$1"
-  elif has_command "nix-shell"; then 
-    nix-shell -p wasmer --run "wasmer $1"
-  else
-    error "Unable to find a WASM runtime to use to run ${BLUE}$1${RESET}!"
-  fi
-else
-
-  if has_command "bun"; then 
-    bun run "$1"
-  elif has_command "deno"; then 
-    deno run "$1"
-  elif has_command "tsx"; then
-    tsx "$1"
-  elif is_javascript "$1" && has_command "node"; then 
-    node "$1"
-  elif has_command "ts-node"; then 
-    ts-node "$1"
-  elif has_command "nix-shell"; then 
-    nix-shell -p bun --run "bun run $1"
-  else 
-    error "${BOLD}${RED}Error:${RESET} failed to find a JS/TS runtime to run ${BLUE}${1}${RESET}\n\nTo run you must install any of the following:\n"
-  fi 
-fi
